apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-nginx-deploy
  namespace: service1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: my-nginx
    spec:
      containers:
      - name: my-nginx-containers
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-services
  namespace: service1
spec:
  selector:
    apps: my-nginx
  type: LoadBalancer
  ports:
    - name: my-nginx-port
      port: 80
      targetPort: 80